### ISSUE TITLE
Forgot Password Feature

### ISSUE THREAD

**Issue by somato-tomato** [austintoddj/canvas#1005]
Hello,

Thank you for creating wonderful package ! i want to ask, Is Forgot Password feature work ? i try to use it but i dont get any email.

Thanks !

**Comment by austintoddj** [comment]
@somato-tomato Do you have a [mail provider](https://laravel.com/docs/8.x/mail#introduction) set up in your application?

**Comment by somato-tomato** [comment]
Thank you for `your` reply!
Yes i have mail provider. i can use forgot password from laravel auth and i receive the reset link, but when i use forgot password in canvas i didnt receive any email.

**Comment by austintoddj** [comment]
Is there anything in the logs? Or just silent fails?

**Comment by somato-tomato** [comment]
Hello,

Sorry for very late reply, its just silent fail. i cant find anything, its just silent fail.

**Comment by austintoddj** [comment]
Do you have a link to the repo by any chance? I can try pulling it down and taking a look.

**Comment by somato-tomato** [comment]
I cant. Ill try create new apps and check again.

**Comment by somato-tomato** [comment]
Should i enable email in config/canvas.php ?

**Comment by austintoddj** [comment]
No. That value is tied to sending out the digest email. Authentication is its own thing.

https://github.com/austintoddj/canvas/blob/master/src/Http/Controllers/Auth/PasswordResetLinkController.php

Do you have [Laravel Telescope](https://github.com/laravel/telescope) installed in the app? That might be a great way to find out where the issue is happening and we can debug from there.
