### ISSUE TITLE
Media Library Feature

### ISSUE THREAD

**Issue by austintoddj** [austintoddj/canvas#19]
Add a media library where users can browser currently uploaded images. A user should also be able to select page images from this library when creating/editing posts.

**Comment by talv86** [comment]
I haven't got a proper solution for this but i have created a branch where you can use the summernote uploader to upload images into blog posts that seems to work quite well as a short term fix if you're interested

**Comment by austintoddj** [comment]
Yeah I'm interested to see that. What's the branch? I'll pull it down and check it out.

**Comment by talv86** [comment]
Sure its "imageUploader". 

I'm working on a proper media browser / uploader which we can trigger from a custom button from the  summernote editor (a long way to go i've only started fleshing it out today) but as a short term work around to allow people to put images into their posts this does what is needed.

**Comment by poklin** [comment]
Hi Guys, how about adding the video for the summer note?

**Comment by austintoddj** [comment]
@poklin As of right now, I'm not seeing a way in Summernote's documentation on how to simply add the video in the toolbar. I can make a completely custom toolbar just fine, but that would remove all the current buttons. If you know of a way, send me a pr.

**Comment by talvbansal** [comment]
I'm hopefully going to have this as a package that can be imported done very soon!

**Comment by austintoddj** [comment]
Sounds good @talvbansal! Can't wait!

**Comment by austintoddj** [comment]
@talvbansal If I pull in `media-manager` right now, is it at the point that I could start working with it to bundle it with Canvas? Or not yet?

**Comment by talvbansal** [comment]
Hey! @austintoddj,

 I just got back from a trip to Russia so sorry for the delay in getting back to you, you can use it at the moment I am in another private project, however I haven't written the docs up yet and before I left I started mapping out a way to make it easier to integrate / use, rather than having to use loads of blade `@import()`s like you currently do I want to be able to create a <media-manager></media-manager> component to set everything up for you so integration is minimal.

Give me some time to work on it and ill keep let you know how i get on

**Comment by austintoddj** [comment]
Thanks for the update @talvbansal, I'll just sit tight for a bit then!
