### ISSUE TITLE
Reading Time for posts

### ISSUE THREAD

**Issue by austintoddj** [austintoddj/canvas#196]
It's helpful for people reading a blog to see the time it will take to read the article before diving into it. This can be accomplished by taking the number of words in the post and dividing it into the average reading speed of an adult (roughly 275 WPM). 

Easiest way to calculate this here is to use PHP's [`str_word_count()`](http://php.net/manual/en/function.str-word-count.php) function, and adding +1 minute to every 275 words. 

**Final output should look like this:**

![screen shot 2016-09-30 at 9 00 49 am](https://cloud.githubusercontent.com/assets/8037011/18994423/61dc94e4-86ed-11e6-9107-574a0f95c3e9.png)

![screen shot 2016-09-30 at 9 00 38 am](https://cloud.githubusercontent.com/assets/8037011/18994429/66b43c74-86ed-11e6-8a10-8b6d656469f7.png)

Anyone is open to take a stab at this!

**Comment by engelju** [comment]
I'd like to take a go at this! Submitting a PR later in the day.

**Comment by cixtor** [comment]
This is an interesting feature request, too bad @engelju already took it, but anyway. Just a few tips to improve the algorithm that will do the counting you should consider to add a score to the words by their complexity instead of their length, for example, reading `[the, is, a, and]` is faster than reading `[speed, helpful, function, average]` and they both have the same count.

Checking the size of each word is obviously a bad idea because the amount of memory increases linearly depending on how big the content is. But you can count the number of appearances of common articles like _"the"_, _"is"_, _"to"_, _"an"_, etc and give them a lower score compared to the other normal words; something like `1-to-5`. Good luck @engelju I am looking forward to see what your approach is going to be.

**Comment by austintoddj** [comment]
@cixtor Thanks for your remarks on this! And just because someone else is taking a stab at it, you can by all means make a branch and PR as well, the more people that contribute to the project, the better it becomes and the more learning is had by everyone. 👍

**Comment by engelju** [comment]
@cixtor I seem to don't find the time to work on this as I thought before, so you go ahead!
