### ISSUE TITLE
Incomplete/Skipped/Risky Test

### ISSUE THREAD

**Issue by austintoddj** [austintoddj/canvas#221]
In the `the_database_table_has_all_of_the_correct_columns()` method of the `PostTagTest.php`, the test passes with exceptions. The error that shows up when this code is not commented out is:

![screen shot 2016-10-12 at 7 25 29 am](https://cloud.githubusercontent.com/assets/8037011/19309943/64445500-904d-11e6-84e2-7606a38373a5.png)

Maybe there's something I'm missing regarding the `erikgall/eloquent-phpunit` package?

Contributors who I thought may be interested or have shown skill in this area:
@erikgall

**Comment by erikgall** [comment]
@austintoddj You're not missing anything.. SQLite databases are different in how they handle foreign keys (they don't really do them by default). So... you can't test foreign key constraints if you are using a SQLite database. 

In the package, if you are using a SQLite database, I skip the test and mark it incomplete (why you see the message). I am going to change how this is handled here in the future. 

https://github.com/erikgall/eloquent-phpunit/blob/master/src/Database/Column.php#L87-L91 

For now, if you want to remove the warning message, delete the foreign key assertion. Otherwise, I would suggest having two databases `canvas` and `canvas_testing` both of which are of the same type (MySQL, PosgreSQL, etc) so the FK's can be tested.

To remove the warning message of a skipped test:

Change this :
```php
$this->table->column('post_id')->integer()->primary()->foreign('post_id', 'id', $onUpdate = 'cascade', $onDelete = 'cascade');
```
To:
```php
$this->table->column('post_id')->integer()->primary();
```

Also, if you want to see more information on why a test failed or was skipped, include the --debug flag when running phpunit. `php vendor/bin/phpunit --debug`

**Comment by austintoddj** [comment]
Great answer @erikgall. Thanks for the heads up. Love utilizing this package in the project btw.
