### ISSUE TITLE
Featured image not working in frontend ...

### ISSUE THREAD

**Issue by mhuijser** [austintoddj/canvas#246]
I'm afraid the featured image is not working anymore, it still worked a week ago ;-) . The image is uploaded in /storage/ , but the blade-template prefixes the path with /assets/. Anyone with this same prob ?

Changing `resources/views/frontend/blog/post.blade.php` and modifying  line 47 from 

`<img src="{{ asset('assets/' . $post->page_image) }}" class="post-hero">`

Back to: 

`<img src="{{ asset($post->page_image) }}" class="post-hero">`

Solves it for me.

Kind regards,

Mark

**Comment by austintoddj** [comment]
@mhuijser Good catch on this. I'll go ahead and make this change as soon as #244 gets fixed. 👍

**Comment by Naoray** [comment]
Sorry, that was my fault. With my last PR I copied all image files to `public/assets/images` because I only checked the 'demo' - blog post with the `mocha.jpg` image, everything did work.

But we, especially me, should have tested more. Actually, does anyone know how we could integrate such things into `tests/`?
