### ISSUE TITLE
/admin/tools route redirects to /admin 

### ISSUE THREAD

**Issue by mhuijser** [austintoddj/canvas#262]
Hi,

Today i've upgraded from v2.1.12 to v2.1.15, but unfortunately it looks like  the "admin/tools"-route  is broken, now.  Anyone else having the same issue ? 

Kind regards, and keep up doin' the good work ! You make beautiful things!

Mark

**Comment by austintoddj** [comment]
@mhuijser Sorry you ran into that issue. The problem is because a suitable upgrade path hasn't been made yet, and the breaking change that you're experiencing is that your user record in the database will either have a Role of `1`(Administrator) or a `0`(User). The administrator will have access to everything on the site, but the normal user will have limited access, only allowing them to publish blog posts. 

When you upgraded to `v2.1.15`, did you create a database from scratch?

**Comment by mhuijser** [comment]
Thanks @austintoddj , no i didn't. But you've pointed me in the right direction.  i'm a litttlebit - how do you say that in english - pigheaded (thanks google translate ;-) ) ...  wanted to upgrade the simple way. I'm very sorry. I didn't notice  the model change there! 

Since i only have one "user" yet,  `update users set role = 1 where id=1;` did the trick, now.

Thanks!
