### ISSUE TITLE
Add a link to 'view' each post (live version) from the posts index page

### ISSUE THREAD

**Issue by connecteev** [austintoddj/canvas#490]
Add a link to 'view' each post (live version) from the posts index page: http://127.0.0.1:8001/canvas/posts

https://prnt.sc/nv9hi3
Add a link to the right of 'Published in 7 hours ― Updated a few seconds ago'

**Comment by austintoddj** [comment]
This was actually a part of the package a few releases ago, until the frontend became separated. From the backend perspective, it doesn't "know" which route the posts are available at since they'd be defined in the Laravel app routes file. 

Would absolutely be up for adding this if you've got a solution.

**Comment by austintoddj** [comment]
Love the idea on this issue, and will absolutely bring it into the project if #923 can be solved. Thanks for bringing it up @connecteev, I'll hopefully circle back to this in the future.
