### ISSUE TITLE
Invalid date

### ISSUE THREAD

**Issue by richard457** [austintoddj/canvas#712]
happend when publishing at Canvas\\Http\\Controllers\\PostController->store does it support L7?

**Comment by austintoddj** [comment]
It does support Laravel 7. What type of database are you using?

**Comment by albertoelias123** [comment]
I believe I had the same problem. I came across an exception from carbon, with the following message:
"Could not parse 'Invalid date-Invalid date-Invalid date Invalid date:Invalid date:00': DateTime::__construct(): Failed to parse time string (Invalid date-Invalid date-Invalid date Invalid date:Invalid date:00) at position 0 (I): The timezone could not be found in the database"

The error occurs when clicking on save a Post. I looked at Network and saw that the problem occurs in an API route (canvas / api / posts) using the POST method

Take a look at the published_at attribute
![image](https://user-images.githubusercontent.com/41304037/83349016-d57c1980-a307-11ea-8b37-de895f704198.png)

**Comment by albertoelias123** [comment]
I discovered the reason for the Bug. When converting a Post to a draft and then clicking Publish Now, it did not set a date and due to this the error occurs. Does anyone have any idea how to solve this? I would be happy to send a PR with the solution, but I really don't know how to proceed


![image](https://user-images.githubusercontent.com/41304037/83349111-9a2e1a80-a308-11ea-9b81-549abe921f4d.png)

**Comment by austintoddj** [comment]
@albertoelias123 Are you able to confirm this bug still exists for you in v6.0.0?

**Comment by albertoelias123** [comment]
Yes, I can, on the weekend I will test this and give you feedback right here
