### ISSUE TITLE
Tag/Topic management

### ISSUE THREAD

**Issue by dgillier** [austintoddj/canvas#716]
Hello,

As far as I understand, each user has it's own list of tag and topic, this can be problematic if each user create his own system...

Anyway to restrict topics (and eventually tags) creation to admin user ?
Thanks, Denis

**Comment by austintoddj** [comment]
I can understand what you're getting at. Canvas doesn't implement a roles/permissions based system, so it'd take a bit of forethought before adding that. The idea behind giving users their own "system" of organization, is so that one user can't delete/edit another users' tag/topic. 

If you're post relied on a specific taxonomy, it'd feel like the rug was ripped out from under you if someone came in and inadvertently removed items.

Does that make senes?

**Comment by dgillier** [comment]
I'm not criticising the current system ;) it makes sense obviously.

I'm wondering if there is a "simple" way to modify the topic/tag management with an external role/permission system ?

**Comment by austintoddj** [comment]
User access restrictions only happen on the top-most level of Canvas, by adding a custom middleware. So, there isn't a simple way to limit _only tag/topic_ editing like you're saying. But there have been a few requests around that sort of functionality, so perhaps I'll find a way to get it into a future release.

**Comment by austintoddj** [comment]
@dgillier Does this system in #750 sound like something you're looking for?

**Comment by dgillier** [comment]
Thanks @austintoddj , Globally accessible stats will be great, globally accessible taxonomy is a great step too...

But personnaly like @canatufkansu, I still think Topics should be set by admin only...

**Comment by austintoddj** [comment]
Added in [v6.0.0](https://github.com/austintoddj/canvas/releases/tag/v6.0.0)
