### ISSUE TITLE
Content Moderator

### ISSUE THREAD

**Issue by ArjunKishore** [austintoddj/canvas#779]
It will be extremely useful to have a content moderator as a feature, such as admin, publisher and author

**Comment by austintoddj** [comment]
Absolutely agree! This feature is coming out in the next version, stay tuned! 😉

**Comment by ArjunKishore** [comment]
can't wait for the new version release

**Comment by vonec** [comment]
any eta on this feature?

**Comment by austintoddj** [comment]
@vonec Hoping to have it out next month. Thanks for being patient.

**Comment by austintoddj** [comment]
@ArjunKishore Just to be clear, the feature that's added to the next release is a simple Admin flag that can be set on the meta data for a user. So, if someone is an Admin, they'll have permission to:

- Access global stats instead of just their own
- Access the Tags/Topics pages to manage the global taxonomy
- Access the Users page to make anyone else an Admin

If you're not an Admin, you'll only be able to:

- See your own stats
- Make posts and create/attach tags/topics through the editor

So, it's not a huge roles-based system, but it should achieve a few elements that people in the community have asked for.

**Comment by vonec** [comment]
it would be great if we can extend the behavior in some way, editors can save drafts, but the publisher will have the ability to publish, this can be quite out of the scope of the base project. Not everyone would require this. Also, the ability to disable stats altogether would be great. Maintaining stats is an overload. so a flag on it would be great. Wish we can contribute a few PR's on to this.

**Comment by austintoddj** [comment]
Thanks for the input @vonec. I do agree with you, and it may be out of the scope for this release to handle roles like that, but I'm not opposed to addressing it in a follow-up release. 

One of the big enhancements to v6 is an integration with [GitPod](http://gitpod.io/). If you haven't used it before, it's absolutely free to make an account by logging in with Github. Once you've done that, check out the [Contributing section](https://github.com/austintoddj/canvas/tree/develop#contributing) in the `develop` branch and click the **Open in GitPod** button 

It'll take a few minutes, so be patient. When it's done, you'll have a full development environment set up, perfectly tailored to working on Canvas. Two terminals will be open, with one setting up and serving the Laravel app, and the other setting up and compiling Canvas. When prompted, you'll be able to open a browser. From here, you're able to code, submit PRs, or do anything you like with the project. I'm pretty happy with it :-)

**Comment by ArjunKishore** [comment]
@austintoddj  Thanks for your reply, I do share @vonec's opinion. I prefer to have a review process before a content gets published. I will see if I can contribute as well, appreciate your efforts.

**Comment by austintoddj** [comment]
@ArjunKishore @vonec 

Since it's a shared opinion, I'll try and get this implemented. If you could, please detail out below, as specifically as you can, the expectations of this feature.

From where it stands right now, the app has **users** and it has **admins**. We can stick with that as being the _role_. Past that, what permissions and abilities do you see the need for?

**Comment by vonec** [comment]
There are two things that i would like to see.

1. Review / Moderation
    a. User can save draft but cannot publish
    b. Admin reviews/edits the post and publishes it.
  
2. Stats should be disabled based on a flag on config. People generally use google analytics, and maintaining views is a database overhead.

**Comment by ArjunKishore** [comment]
user has three different types of permission  Author, Publisher and Admin

**Author** has lowest level of access

- Add New Pages and content - and assign it to a publisher/admin for review
- Publish Content - No

**Publisher** has medium level access

- Can access all pages and drafts
- Can publish and un publish any pages

**Admin** has highest level of access

- Can access all pages and drafts
- Can publish, un publish and delete any page
- Can grant or revoke access to all users

I don't have any problems with stats, in fact its very helpful that we don't have to rely on external analytics.

**Comment by austintoddj** [comment]
Good thoughts @ArjunKishore @vonec, thanks for being clear with what you wanted to see in there. Since the admin role is currently already built into the develop branch, it shouldn't be too difficult to tweak the existing logic and allow for 3 roles. 

The stats are going to remain as-is, just because it's an integral part of the project. 

If you've got further thoughts on it, feel free to let me know.

**Comment by vonec** [comment]
is the stats are to be retained they shd be the secondary thing we should be doing, for a content writer like medium, the focus should be on content creation. kindly consider having the posts on top and stats on a  panel :)

**Comment by austintoddj** [comment]
Quick update for @vonec and @ArjunKishore and anyone else who follows this ;)

In the process of implementing some basic roles, it turned out to be far more economical to write an entire Auth system into the project. Going forward, we'll replace the `canvas_user_meta` table with `canvas_users` that can store all the login/meta/role information. 

As it stands, we've got 3 roles:

- Contributor (somebody who can write and manage their own posts but cannot publish them)
- Editor (somebody who can publish and manage posts including the posts of other users)
- Admin (somebody who can do everything and see everything)

When you install a fresh version of Canvas into a project, you'll get a default Admin user with basic credentials given through the console. Once in the app, you can perform all the CRUD operations you'd like on further users. The only thing you won't be able to do is delete or change your own role, for obvious reasons.

I'm still hoping to get this out by the end of this month, but the addition of these features makes it a bit tighter than before. Still, I'm extremely happy with where it's at, and I'll get this launched as soon as possible.

**Comment by vonec** [comment]
wow ... waiting to test it

**Comment by ArjunKishore** [comment]
@austintoddj Thanks a lot, really looking forward to it.

**Comment by austintoddj** [comment]
Added in [v6.0.0](https://github.com/austintoddj/canvas/releases/tag/v6.0.0)
