### ISSUE TITLE
Publish the vendor views

### ISSUE THREAD

**Issue by capricorn05** [austintoddj/canvas#809]
Hi,
Is there a way to publish the vendor views for the back-end to integrate them into existing app?

**Comment by austintoddj** [comment]
Are you trying to publish them so you'd be able to edit/modify the Vue components yourself?

There isn't a way to do that with the current setup, since doing that would make upgrade paths nearly un-manageable.

If there is something that you'd like to see integrated that isn't already in there, let me know and I'll do my best to get it in.

**Comment by capricorn05** [comment]
Hi,Thanks for getting back to me so quickly.  I was hoping to incorporate my existing left nav bar for the remainder of the app into the blog section.Could I create my own layout page and link to the canva app.js etc?Thanks

**Comment by austintoddj** [comment]
Ah I see. Unfortunately, it isn't possible to make Canvas fit into existing layouts like that. 

Wish I had a better answer for you. I will say that v6 is right around the corner and has some nice visual enhancements, so even though it won't sit in the layout of an existing app, it does look pretty nice :-)
