### ISSUE TITLE
Target class [Canvas\Http\Middleware\ViewThrottle] does not exist.

### ISSUE THREAD

**Issue by GigaMick** [austintoddj/canvas#861]
Getting the above error when navigating to a post.

No idea what to do to fix it.

Please help 🙏

**Comment by austintoddj** [comment]
So the `ViewThrottle` middleware name changed to `Session`. If you check the [latest releases](https://github.com/austintoddj/canvas/releases) you'll see there have been a number of changes since that happened.

Check out the [upgrade guide](https://github.com/austintoddj/canvas/blob/master/.github/UPGRADE.md) and see the steps to bring your installation up to the latest.

Let me know if you have other questions or run into any issues.

**Comment by GigaMick** [comment]
Hi Thanks for the reply. I appreciate it.

I think I upgraded in a really crazy way. I removed completely canvas/canvas (I was on version 4.something) and then installed the latest austintoddj/canvas. I managed to work out a lot of that upgrade guide by myself but the viewthrottle thing is killing me. I can't find it referenced anywhere! 

Here is my stack trace:
https://flareapp.io/share/DPyL1VRm#F47

Can you point me in a direction?

Thanks!
