### ISSUE TITLE
Migrate Fresh deletes default user installed with canvas:install command

### ISSUE THREAD

**Issue by hexpit** [austintoddj/canvas#868]
Migrate Fresh deletes default user installed with canvas:install command

**Comment by austintoddj** [comment]
You're right. Haven't actually run into that issue myself.

I'm not sure there's a good way around that since in a production environment, you wouldn't be running the `migrate:fresh` command anyway.

The `canvas:user` command that's built into the project is available however to make a new user on the fly if need be.
