### ISSUE TITLE
Built-in Auth System

### ISSUE THREAD

**Issue by workfransiskusferdian** [austintoddj/canvas#902]
It is possible to install canvas without its built-in auth system or make its password hashing the same as jetstream hash? I use laravel 8 with jetstream, and when I log in to my own admin dashboard I can't directly access canvas, this feel bit awkward when I have to re-enter my email and password which are the same to access canvas. Thank You

**Comment by austintoddj** [comment]
At this point in time, no. While Canvas used to work off of Laravel's base login system, it was changed in v6 to allow more flexibility to the package.

That being said, I believe there's more than likely a way to implement this. I'll keep this in mind moving forward, and see if it's a viable feature in an upcoming release.

**Comment by workfransiskusferdian** [comment]
well, thank you..

**Comment by marvinhosea** [comment]
I think Canvas having its own auth system does not encourage flexibility considering anyone can include auth quickly and without any problem in Laravel.

**Comment by austintoddj** [comment]
You're right @marvinhosea, but then there's a problem of different auth systems having various underlying properties. Canvas relies quite a bit on the packages' User model now so that it can access various relationships.

The flexibility actually _increases_ having the new auth system, since prior to it there could be a situation like such as this:

Your auth system doesn't use `id` as it's primary key, or there isn't a Post relationship. And most assuredly, not every auth system is going to have a `summary`, `avatar`, etc.

That being said, what would you add to the auth scaffolding that would increase the flexibility in your eyes?

**Comment by marvinhosea** [comment]
Sorry for replying to this late but all that can be included in the config and in case there is no avatar you can avatar the name initials. 

I will PR when I get time for approval. Thanks
